Milestone 2 - Bookstore
Azeem838/bookstore-react pull request #2
Opened 2020-09-25 16:13 UTC by Azeem838

In this milestone, we accomplished the following:

1. Prepared the project directory with components, containers, actions and reducers.
2. Implemented the App Component
3. Implemented the BookList component that listed all the books in a table
4. Implemented the Book component that created a row for a book
5. Implemented the Book form component that displayed a form
6. Defined Redux actions and reducers
7. Initialized the Redux store and the initial state

Please find our commit below,
Thank you.

2020-09-26 20:33 UTC, shloch requested changes
## Hello @Azeem838 , @PhillipUg 

Hello guys, everything is cool here.......this is awesome from you
The modification I will ask you to bring is with respect to requirements, nothing logical before we get final thumbs up

See comment below : 

Happy coding

2020-09-26 20:33 UTC, shloch commented on src/components/BookList.js
> +import Book from './Book';
- this component is a "container" component and should be in the `src/containers/` folder

2020-09-26 20:33 UTC, shloch commented on src/components/BookForm.js
> +
- this component is a "container" component and should be in the `src/containers/` folder

2020-09-27 07:27 UTC, PhillipUg commented
As recommended, we have fixed the following:
- moved `BookList` and `BookForm` components to the containers folder.

2020-09-27 22:06 UTC, jofer86 approved these changes
## `const PROJECT_STATUS = "APPROVED"` 🚀 🚀 🚀 
## :wave: :wave: Hello! I'm Jorge, and  I will be conducting this code review. Let me get a closer look 🔎 🔍 🔎 🔍 🕵🏼 
- Changes marked as **[OPTIONAL]** are not hard requirements but are nice to have.
- All of the required changes were compliant with the required changes.
--------------------------------------------------------------------
**Rock on**  🤘🏼 
**_Jorge Fernando Rincón Figueroa._** 
Technical Support Engineer.

2020-09-28 06:33 UTC, merged